name: ci
on: [push]
jobs:
  cibuild:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16beta1
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt update && sudo apt install build-essential libgtk-3-dev libcairo2-dev libglib2.0-dev libglib2.0-dev-bin
    - name: Test
      run: make
